[package]
name = "location_monitor_rust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rosrust = "0.9.6"
rosrust_msg = "0.1.2"
env_logger = "0.8.4"
static-math = "0.2.0"
